describe("selection", function()
    it("drops the empty line at either end of a copied selection", function()
        local Selection = require("ito.window.selection")
        local selection = Selection()
        selection.rows = { [0] = "first line", [1] = "second", [2] = "", [3] = "fourth" }
        selection:press(0, 0, 0)
        selection:drag(0, 1)
        assert.equal("first line", selection:release(), "a drag that ends at the start of the next row")
        selection:clear()
        selection:press(10, 0, 10)
        selection:drag(6, 1)
        assert.equal("second", selection:release(), "a drag that starts past the end of a line")
        selection:clear()
        selection:press(0, 1, 20)
        selection:drag(6, 3)
        assert.equal("second\n\nfourth", selection:release(), "blank lines inside the selection stay")
    end)
end)
