local screen = require("support.screen")

describe("styles", function()
    local kit = require("ito")

    local function raises(message, call, ...)
        local ok, err = pcall(call, ...)
        assert.is_false(ok, message)
        assert.truthy(tostring(err):find(message, 1, true), "expected " .. message .. ", got " .. tostring(err))
    end

    it("makes colours and styles values that equal each other when their fields do", function()
        assert.equal(kit.rgb(0x102030), kit.rgb(0x102030))
        assert.equal("#102030", tostring(kit.rgb(0x102030)))
        assert.equal("cyan", tostring(kit.Color.cyan))
        assert.equal(kit.Color.indexed(236), kit.Color.indexed(236))
        assert.equal(kit.Color.indexed(12), kit.Color.indexed(24 / 2))
        assert.equal("12", tostring(kit.Color.indexed(12.0)))
        local accent = kit.TextStyle({ foreground = kit.Color.cyan, bold = true })
        assert.equal(accent, kit.TextStyle({ bold = true, foreground = kit.Color.cyan }))
        assert.equal(kit.TextStyle(), kit.TextStyle({ bold = false }))
        assert.are_not.equal(accent, kit.TextStyle({ foreground = kit.Color.cyan }))
        assert.equal(kit.Color.cyan, accent.foreground)
        assert.is_true(accent.bold)
        assert.is_nil(accent.italic)
    end)

    it("merges one style on top of another", function()
        local base = kit.TextStyle({ foreground = kit.Color.white, background = kit.Color.blue, italic = true })
        local head = kit.TextStyle({ foreground = kit.Color.red, bold = true })
        local merged = base:merge(head)
        assert.equal(kit.TextStyle({ foreground = kit.Color.red, background = kit.Color.blue, italic = true, bold = true }), merged)
        assert.equal(merged, base:merge(head))
        assert.equal(base, base:merge(kit.TextStyle()))
        assert.equal(base, base:merge(nil))
    end)

    it("refuses fields that are not colours or flags, and does not change", function()
        raises("a TextStyle's foreground must be an ito.Color, not a string", kit.TextStyle, { foreground = "cyan" })
        raises("a TextStyle has foreground, background, bold", kit.TextStyle, { glow = true })
        raises("a TextStyle's bold must be true or false, not a number", kit.TextStyle, { bold = 1 })
        raises("ito.TextStyle takes a table of fields, not a string", kit.TextStyle, "bold")
        raises("ito.Color.indexed takes a whole number from 0 to 255, not 300", kit.Color.indexed, 300)
        raises("ito.rgb takes a colour such as 0xd4d4d4", kit.rgb, "#d4d4d4")
        raises("merge takes an ito.TextStyle, not a table", function()
            return kit.TextStyle():merge({ bold = true })
        end)
        raises("an ito.TextStyle cannot change", function()
            kit.TextStyle().bold = true
        end)
        raises("an ito.TextStyle cannot change", function()
            kit.TextStyle({ bold = true }).bold = nil
        end)
        raises("an ito.Color cannot change", function()
            kit.Color.red.spec = "#00ff00"
        end)
        assert.equal("ito.TextStyle", getmetatable(kit.TextStyle()))
        assert.equal("red", tostring(kit.Color.red))
        assert.is_true(kit.TextStyle({ bold = true }).bold)
        raises("foreground must be an ito.Color, not a number", function()
            return kit.Text("x"):foreground(214)
        end)
        raises("background must be an ito.Color, not a string", function()
            return kit.Text("x"):background("#102030")
        end)
        raises("a border's color must be an ito.Color, not a number", function()
            return kit.Text("x"):border(screen.THEME.borders.plain, { color = 196 })
        end)
        raises("style must be an ito.TextStyle, not a table", function()
            return kit.Text("x"):style({ bold = true })
        end)
    end)

    it("draws text and spans in their styles", function()
        local s = screen.new(20, 3)
        local note = kit.TextStyle({ foreground = kit.rgb(0xff8800), underline = true })
        s:show(function()
            return kit.VStack({
                kit.Text("note"):style(note):bold(),
                kit.Lines({ { { "a", kit.TextStyle({ background = kit.Color.indexed(236) }) }, { "b" } } }),
            })
        end)
        local first = s.screen:spans(0)[1]
        assert.equal("note", first.text)
        assert.equal("#FF8800", first.fg)
        assert.same({ "bold", "underline" }, first.modifiers)
        local second = s.screen:spans(1)
        assert.equal("236", second[1].bg)
        assert.equal("b", second[2].text:sub(1, 1))
        assert.is_nil(second[2].bg)
    end)

    it("refuses a span or a paint whose style is not a TextStyle", function()
        local tty = require("ito.tty").virtual(4, 1)
        local area = { x = 0, y = 0, width = 1, height = 1 }
        raises("a style is an ito.TextStyle, not a number", tty.line, tty, 0, 0, { { "x", 3 } })
        raises("a style is an ito.TextStyle, not a table", tty.line, tty, 0, 0, { { "x", {} } })
        raises("a style is an ito.TextStyle, not a table", tty.line, tty, 0, 0, { { "x", kit.Color.red } })
        raises("paint needs an ito.TextStyle", tty.paint, tty, area)
        raises("a style is an ito.TextStyle, not a number", tty.paint, tty, area, 9999)
        tty:paint(area, kit.TextStyle({ reverse = true }))
        assert.same({ "reverse" }, tty:spans(0)[1].modifiers)
    end)
end)
